spring:
  server:
    port: 8080
    address: 0.0.0.0
  redis:
    host: redis-container
    port: 6379
  datasource:
    url: jdbc:mysql://ar7-db-sit-do-user-15535699-0.g.db.ondigitalocean.com:25060/ar7_db_sit?sessionVariables=sql_require_primary_key=0
    username: ar7-db
    password: AVNS_rzOj8asvSv0scu0Phfe
    #    url: jdbc:mysql://localhost:3306/ar7_database
    #    username: kyawgyi
    #    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

file:
  upload-dir: ./upload-dir

logging:
  level:
    org:
      springframework.jdbc.core: TRACE
      com.zaxxer.hikari: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

digitalocean:
  spaces:
    key: DO00QY2JJUB98BDQQT4Z
    secret: WAlVi0mGxQVNg2o3QHjlAeBN0m9UceLeHl/CzLJyVVM
    endpoint: https://sgp1.digitaloceanspaces.com
    region: sgp1
    bucket-name: ar7imageserversit

cloud:
  aws:
    credentials:
      access-key: DO00QY2JJUB98BDQQT4Z
      secret-key: WAlVi0mGxQVNg2o3QHjlAeBN0m9UceLeHl/CzLJyVVM
    region:
      static: sgp1
    stack:
      auto: false